### ISSUE TITLE
After every deploy DJ is starting from strach 

### ISSUE THREAD

**Issue by SergeyKishenin** [platanus/capistrano3-delayed-job#16]
```
DEBUG [bf6fd0e9] 	delayed_job.0: warning: no instances running. Starting...
DEBUG [bf6fd0e9] 	delayed_job.0: process with pid 6812 started.
DEBUG [bf6fd0e9] 	delayed_job.1: warning: no instances running. Starting...
DEBUG [bf6fd0e9] 	
DEBUG [bf6fd0e9] 	delayed_job.1: process with pid 6818 started.
DEBUG [bf6fd0e9] 	delayed_job.2: warning: no instances running. Starting...
DEBUG [bf6fd0e9] 	delayed_job.2: process with pid 6824 started.
```

While instances are already running.

My cap setup is:

```
set :delayed_job_workers, 3
set :delayed_job_roles, [:web]
```

Also I have

```
set :linked_dirs, %w{pids}
```

Can you advise?

**Comment by blackjid** [comment]
Yes, this gem is adding that.
https://github.com/platanus/capistrano3-delayed-job/blob/master/lib/capistrano/tasks/delayed-job.rake#L53-L55

do you think it shouldn't?

**Comment by SergeyKishenin** [comment]
Yes. But I mean

> While instances are already running.

I have already 3 DJ processes and after deploy another 3 appear.

**Comment by blackjid** [comment]
sorry, I didn't get that...

I think you are having this issue https://github.com/platanus/capistrano3-delayed-job/issues/7

You should symling you `tmp/pids` folder instead of just `pids`

```
set :linked_dirs, %w{tmp/pids}
```

**Comment by SergeyKishenin** [comment]
That works. Thanks a lot!
