### ISSUE TITLE
Wrong order in specifying the command and options? 

### ISSUE THREAD

**Issue by maleko** [platanus/capistrano3-delayed-job#2]
Hi I got an error when trying to deploy. 

```
[572c5aad] Command: cd /webapps/test/releases/20150107035218 && ( RAILS_ENV=production /usr/local/rvm/bin/rvm default do bundle exec bin/delayed_job -n 1 --queues=Test1,Test2 --pool=Test1:2 --pool=Test2:2 --pool=*:2 restart )
DEBUG [572c5aad] 	ERROR: no command given
```
From what I gather from the [command.rb](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/command.rb), it states that the command must be specified first before the options. 

Would you be able to fix this? Thanks! 

Cheers

**Comment by blackjid** [comment]
hey!, this is weird. I've been using this gem in a few projects, without any problems...

for example this capistrano output worked fine

```
[573bc812] Command: cd /home/deploy/applications/amigosecreto/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=1.9.3 NODENV_ROOT=~/.nodenv NODENV_VERSION= RAILS_ENV=staging ~/.rbenv/bin/rbenv exec bundle exec script/delayed_job -n 1 --queues=mailer,tracking --pool=mailer:2 --pool=tracking:1 --pool=*:2 start )
```

Are you sure that that error `ERROR: no command given` is from delayed_job?? may be is from nvm....

Are you using rails 4?? in rails 3, the delayed_job script is in the `script` folder instead of bin.....
If you are in rails 3 you'll need to add 

```ruby
set :delayed_job_bin_path, 'script' # for rails 3.x
```

that's everything I can think of right now...

**Comment by maleko** [comment]
Yup, pretty sure it's from delayed job. I ran the command on local and it bombed out too. my versions are:

```
  * capistrano (3.3.5)
  * capistrano-bundler (1.1.3)
  * capistrano-deploytags (1.0.0)
  * capistrano-faster-assets (1.0.2)
  * capistrano-passenger (0.0.1)
  * capistrano-rails (1.1.2)
  * capistrano-resque (0.2.1)
  * capistrano-rvm (0.1.2)
  * capistrano-stats (1.1.1)
  * capistrano3-delayed-job (1.2.1 0459514) [I forked it to change the order of the command]
  * delayed_job (4.0.6)
  * delayed_job_active_record (4.0.2)
  * rails (4.1.8)
```

The delayed_job script is in ```bin``` coz I am using Rails 4. When I run ```bin/delayed_job``` locally, I get the following output:

```
ERROR: no command given

Usage: delayed_job <command> <options> -- <application options>

* where <command> is one of:
  start         start an instance of the application
  stop          stop all instances of the application
  restart       stop all instances and restart them afterwards
  reload        send a SIGHUP to all instances of the application
  run           start the application and stay on top
  zap           set the application to a stopped state
  status        show status (PID) of application instances

* and where <options> may contain several of the following:

    -t, --ontop                      Stay on top (does not daemonize)
    -f, --force                      Force operation
    -n, --no_wait                    Do not wait for processes to stop

Common options:
    -h, --help                       Show this message
        --version                    Show version
```

It states to use the command first. I'm a bit confused myself. lol.

**Comment by blackjid** [comment]
mm yes you are right. But I tried locally with command in both places and it worked fine in both...

did it work the fork you made to this gem where you changed the order?

on the other hand the cap task proposed by the delayed_jobs team use the command at the end. https://github.com/collectiveidea/delayed_job/wiki/Delayed-Job-tasks-for-Capistrano-3

**Comment by maleko** [comment]
Yup, it is extremely unusual. I wonder if it’s because I’m using Zsh but it fails on the server and it’s using Bash. 

It worked ok on my fork once I changed the order.

Yeah I saw that on the delayed_jobs team. Perhaps it might be good if we ping them and see what changed recently or something. lol. 

Thanks for checking up on this!

**Comment by blackjid** [comment]
i'm going to close this, a it looks to be an environment problem..... please let me know if you make it work, or feel free to reopen it if you think it is a problem in this gem

**Comment by rab** [comment]
It "works" with the command at the end because the arguments are destructively consumed so all that's left in the args is the command. The daemons gem indicates that the command args _should_ be first and separated from the app's args by the standard `--`.
