### ISSUE TITLE
require statement should use underscore

### ISSUE THREAD

**Issue by lotrdev** [platanus/capistrano3-delayed-job#25]
It took me far to long to realize this but the code mentioned int he readme:
```require 'capistrano/delayed-job'```
doesn't work because the filename is delayed_job.rb. The readme should read:
```require 'capistrano/delayed_job'```

**Comment by blackjid** [comment]
wow sorry, thanks!... would you mind to open a PR with the fix?? thanks!

**Comment by lotrdev** [comment]
Sure: https://github.com/platanus/capistrano3-delayed-job/pull/26

**Comment by blackjid** [comment]
are you sure about this??
the file name is [lib/capistrano/delayed-job.rb](https://github.com/platanus/capistrano3-delayed-job/blob/master/lib/capistrano/delayed-job.rb) i've been using this with `require 'capistrano/delayed-job` and it works fine
