### ISSUE TITLE
Offer to become Maintainer

### ISSUE THREAD

**Issue by rab** [platanus/capistrano3-delayed-job#32]
As I'll be using Capistrano for deployment for the foreseeable future, I can assume the maintenance role for this gem. I'd do so on my [fork](https://github.com/AgileConsultingLLC/capistrano3-delayed-job)

**Comment by rab** [comment]
Hey, @blackjid , I was just wondering what you thought of my offer?

**Comment by blackjid** [comment]
Hey, sorry for the delay...
Thanks for your offering...  let's talk by email. ok?
