### ISSUE TITLE
Delayed Job failed:  fetching files from old capistranio releases

### ISSUE THREAD

**Issue by sumit20rai** [platanus/capistrano3-delayed-job#34]
I am using delayed-job gem and capistrano3-delayed-job to manage my jobs while deploying code via capistrano for my Rails 4 application.

The delayed jobs are failing and i'm getting **"can not load translations from /home/bot/getsavvy-api/releases/20170419152135/config/locales/devise.en.yml: #<Errno::ENOENT: No such file or directory @ rb_sysopen"** error on production after 2-3 days of deployment.

It looks like its fetching files from old releases which are not present on server anymore.

I have following in my deploy.rb file

```
`set :delayed_job_workers, 4 

set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'public/system')
`
```
Any idea how to resolve this issue?

**Comment by blackjid** [comment]
can you please ask here https://github.com/AgileConsultingLLC/capistrano3-delayed-job/issues

This repo is no longer maintained.

Looks like you are not restarting the delayed-jobs processes after the deploy.
