### ISSUE TITLE
Warning: no instances running on deploy

### ISSUE THREAD

**Issue by patrickbrownsync** [platanus/capistrano3-delayed-job#9]
Whenever I deploy using:

`bundle exec cap production deploy`

The command executed to restart delayed job is:
`cd /var/www/app/releases/20150319211025 && ( RAILS_ENV=production /usr/bin/env bundle exec bin/delayed_job -n 4 restart )`

I get the message "Warning: no instances running. Starting..." which seems to be leaving my old delayed job instances running.

However if I manually run:

`bundle exec cap production delayed_job:restart`

The code run is:
`cd /var/www/app/current && ( RAILS_ENV=production /usr/bin/env bundle exec bin/delayed_job -n 4 restart )`

 I correctly get "delayed_job: process with pid 13245 successfully stopped"

I think the issue is the difference between current and the release version but I'm not sure why that difference is happening.

Thanks

Rails 4.1.8, ruby 2.1.3

**Comment by blackjid** [comment]
are you symlinking your `tmp/pids` folder?? 

```rb
set :linked_dirs, fetch(:linked_dirs, []) + %w{log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
```

can you try that if you're not?

**Comment by patrickbrownsync** [comment]
That fixed it, thanks a lot!

**Comment by blackjid** [comment]
:)  :+1:
